env:
  global:
    - CC_TEST_REPORTER_ID=f8edcd00ce06ade020fa17a66b2481c4464fac216903f7f4a5fcfc04b457159e
language: ruby
rvm:
- 2.2.5
- 2.5.1
before_script:
  - psql -c 'create database order_as_specified_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
  - bundle exec rubocop
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
addons:
  postgresql: "9.3"
env:
  matrix:
    - AR_VERSION="~> 5.0.0"
    - AR_VERSION="~> 5.1.0"
    - AR_VERSION="~> 5.2.0"
notifications:
  email: false
  hipchat:
    rooms:
      secure: pLL6WXsWnvigZNgcYYwr0el3AG3WbRXOV4zAoBx/pAD/y51/KOjWboUO5szOqIicdSBJTIY5el7wK4uUi5elseumjl1jvOQSG7izvCGzDekuJuOTj9f6MdLtigbIaWO5/NWtXw0/JGHDQJpB4HyOv1mGAjQ3Y6MKxMNv+RUsgRI=
